name: DiabetesCalculatoriOS
options:
  minimumXcodeGenVersion: 2.44.1
settings:
  base:
    SWIFT_VERSION: 5.10
    DEVELOPMENT_TEAM: ""
    PRODUCT_BUNDLE_IDENTIFIER: com.diabetes.calculator.ios
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
configs:
  Debug: debug
  Release: release
targets:
  DiabetesCalculatoriOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DiabetesCalculatoriOS
        excludes:
          - "**/*.md"
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: DiabetesCalculator
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_UIRequiresFullScreen: NO
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.medical
        GENERATE_INFOPLIST_FILE: YES
    info:
      path: DiabetesCalculatoriOS/Resources/Info.plist
      properties:
        UILaunchStoryboardName: ""
        UIApplicationSupportsIndirectInputEvents: true
        NSUserNotificationUsageDescription: "Se usan notificaciones para recordar la medición de glucosa 2h tras una comida."
        CFBundleDevelopmentRegion: es
schemes:
  DiabetesCalculatoriOS:
    build:
      targets:
        DiabetesCalculatoriOS: all
    run:
      config: Debug
    archive:
      config: Release
